### ISSUE TITLE
感觉有些配置有点问题，编译出来的apk找不到对应so，这块简单修改下就好了

### ISSUE THREAD

**Issue by chengzeyuan** [hanliang-tech/CastAgent#1]

**Comment by chengzeyuan** [comment]
--------- beginning of crash
10-21 16:14:13.626  7149  7149 E AndroidRuntime: FATAL EXCEPTION: main
10-21 16:14:13.626  7149  7149 E AndroidRuntime: Process: com.ex.unisen.cast, PID: 7149
10-21 16:14:13.626  7149  7149 E AndroidRuntime: java.lang.NoClassDefFoundError: com.qiniu.qplayer.mediaEngine.MediaPlayer
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at com.pili.pldroid.player.PLMediaPlayer.<init>(PLMediaPlayer.java:47)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at com.pili.pldroid.player.widget.a.a(PLBaseVideoView.java:628)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at com.pili.pldroid.player.widget.a$3.a(PLBaseVideoView.java:1243)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at com.pili.pldroid.player.widget.PLVideoView$a$1.surfaceCreated(PLVideoView.java:140)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.SurfaceView.updateSurface(SurfaceView.java:904)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:146)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.-$$Lambda$SurfaceView$w68OV7dB_zKVNsA-r0IrAUtyWas.onPreDraw(Unknown Source:2)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2770)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1746)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7775)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1184)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:954)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:888)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1169)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7535)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
10-21 16:14:13.626  7149  7149 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ex.unisen.cast-KlRggnZvn0WqvK5x58t7TA==/base.apk"],nativeLibraryDirectories=[/data/app/com.ex.unisen.cast-KlRggnZvn0WqvK5x58t7TA==/lib/arm, /data/app/com.ex.unisen.cast-KlRggnZvn0WqvK5x58t7TA==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]] couldn't find "libQPlayer.so"
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at java.lang.System.loadLibrary(System.java:1667)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        at com.qiniu.qplayer.mediaEngine.MediaPlayer.<clinit>(MediaPlayer.java:123)
10-21 16:14:13.626  7149  7149 E AndroidRuntime:        ... 22 more
10-21 16:14:13.627  1448  1853 W ActivityTaskManager:   Force finishing activity com.ex.unisen.cast/com.ex.unisen.activity.VideoPlayerActivity
